kind: ConfigMap
apiVersion: v1
metadata:
  name: credentials
  namespace: quepid
data:
  DATABASE_URL: "mysql2://user:password@host:3306/db"
  REDIS_URL: "redis://hostname:6379/db"
  SECRET_KEY_BASE: "<some randon string>"
