kind: ConfigMap
apiVersion: v1
metadata:
  name: credentials
  labels:
    {{- include "quepid_chart.labels" . | nindent 4 }}
data:
  DATABASE_URL: "{{ .Values.credentials.database_url }}"
  REDIS_URL: "{{ .Values.credentials.redis_url }}"
  SECRET_KEY_BASE: "{{ .Values.credentials.secret_key_base }}"
