---
apiVersion: v1
kind: Service
metadata:
  name: quepid
  namespace: quepid
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
      name: http
  selector:
    app: quepid
