---
apiVersion: v1
kind: Service
metadata:
  name: quepid
  labels:
    {{- include "quepid_chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
      name: http
  selector:
    app: quepid
