---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quepid
  labels:
    app: quepid
spec:
  selector:
    matchLabels:
      app: quepid
  replicas: 1
  template:
    metadata:
      labels:
        app: quepid
    spec:
      containers:
        - name: quepid
          image: o19s/quepid:7.9.2
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "550m"
              memory: "500Mi"
            limits:
              cpu: "650m"
              memory: "500Mi"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
          envFrom:
            - configMapRef:
                name: common
            - configMapRef:
                name: credentials
      restartPolicy: Always
